# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:

language: python

python:
  - "3.5"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3-dev swig

install:
  - python setup.py bdist_wheel
  - pip install dist/*.whl

script:
  - pytest
