# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:

language: python

python:
  - "3.5"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y swig

install:
  - python setup.py bdist_wheel

script:
  - pytest setup.py test
  - pip install dist/*.whl
  - pytest
