# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:

sudo: false

language: python

python:
  - "3.5"

addons:
  apt_packages:
    - swig

install:
  - python setup.py bdist_wheel
  - pip install dist/*.whl

script:
  - python setup.py test
  - pytest
